name: secondevaluation
description: "Book and Bite is an app that provides cafeteria, bookshop and complaint service."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  animate_do: ^3.1.2
  firebase_core:
  firebase_auth:
  firebase_storage:
  lottie: ^3.0.0
  shared_preferences: ^2.2.3
  firebase_database:
  image_picker: ^1.0.8
  carousel_slider:
  path_provider: ^2.0.6
  gallery_saver: ^2.3.2
  flutter_image:
  flutter_local_notifications: ^17.1.2
  file_picker: ^8.0.3
  js: ^0.7.1
  cloud_firestore: ^4.17.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # https://flutter.dev/assets-and-images/#resolution-aware

  # https://flutter.dev/assets-and-images/#from-packages

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
